
############################################
#                                          #
#            PRIVATE MESSAGE+              #
#           THANKS FOR BUYING!             #
#                                          #
############################################


# MESSAGE || for colors - https://docs.advntr.dtev/minimessage/format.html
recieved-msg: "<aqua>From %player%: %message%"
sent-msg: "<aqua>To %target%: %message%"
not-messaged: "<red>You have not been messaged before!"
reply-offline: "<red>The player is offline!"


# SOCIAL SPY || for colors - https://docs.advntr.dev/minimessage/format.html
spy-perm: "spy.admin"
spy-noperm-msg: "<red>You don't have the required permission!"
spy-msg: "<gold>[SOCIALSPY] <aqua>%player% > %target%: %message%"
spy-toggle-on: "<gold>[SOCIALSPY] <green>You have turned on SocialSpy"
spy-toggle-off: "<gold>[SOCIALSPY] <red>You have turned off SocialSpy"


# RELOAD || for colors - https://docs.advntr.dev/minimessage/format.html
reload-msg: "<gold>successfully reloaded config!"
reload-noperm-msg: "<red>You don't have the required permission!"
reload-perm: "pmplus.reload"