name: PMPlus
version: '${version}'
main: PRIVATEMSGPLUS.zypq.PMPLUS
author: zypq
api-version: '1.20'
description: spigotlink
commands:
  message:
    aliases:
      - dm
      - m
      - pm
      - message
  SocialSpy:
      aliases:
        - ss
        - spy
        - msgspy
        - staffspy
  reply:
    aliases:
      - r
  PMPLUS:
     aliases:
       - PMP

